### ISSUE TITLE
error when run 'mamba env create -f environment.yaml'

### ISSUE THREAD

**Issue by lanshui98** [rajewsky-lab/spacemake#124]
Got this error:

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - star[version='>=2.7.1a']
  - bcl2fastq2[version='>=2.19']
  - sambamba[version='>=0.6.8']

Can you help with this?

**Comment by nukappa** [comment]
Hi, are you by any chance trying to install spacemake on MacOS? We know that certain packages (bcl2fastq being one) are not easily available there.

**Comment by lanshui98** [comment]
Yes I was trying to install it on MacOS. I tried to install it on Windows instead. But I was reviewing the star package which doesn't recommend Windows. Should I try Linux instead?

**Comment by nukappa** [comment]
Yes, if you have access to Linux, that would be preferred. You might get around with using the Linux Subsystem in Windows, though.
