### ISSUE TITLE
Error "version" with spacemake config add_species

### ISSUE THREAD

**Issue by Noemie-B** [rajewsky-lab/spacemake#34]
Hi ! After downloading human data, I try to launch spacemake config add_species with the following command :
spacemake config add_species --name human --genome PATH/species_data/human/GRCh38.primary_assembly.genome.fa.gz --annotation PATH/species_data/human/gencode.v38.primary_assembly.annotation.gtf.gz 
but I have the error : 

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/spacemake/bin/spacemake", line 8, in <module>
    sys.exit(cmdline())
  File "/home/user/anaconda3/envs/spacemake/lib/python3.9/site-packages/spacemake/smk.py", line 611, in cmdline
    func(args)
  File "/home/user/anaconda3/envs/spacemake/lib/python3.9/site-packages/spacemake/config.py", line 234, in <lambda>
    func = lambda args: add_update_delete_variable_cmdline(config, args)
  File "/home/user/anaconda3/envs/spacemake/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/user/anaconda3/envs/spacemake/lib/python3.9/site-packages/spacemake/config.py", line 305, in add_update_delete_variable_cmdline
    var_variables = func(variable, name, **args)
  File "/home/user/anaconda3/envs/spacemake/lib/python3.9/site-packages/spacemake/config.py", line 661, in add_variable
    values = self.process_variable_args(variable, **kwargs)
  File "/home/user/anaconda3/envs/spacemake/lib/python3.9/site-packages/spacemake/config.py", line 655, in process_variable_args
    return self.process_species_args(**kwargs)
TypeError: process_species_args() got an unexpected keyword argument 'version'

Do you know this problem, and if yes, can you please help me to overcome it ? Thanks in advance for your answer !

**Comment by nukappa** [comment]
Hi there, it might be that we lack support for zipped files, could you try unzipping your genome/annotation files and see if that solves the issue?

**Comment by sztankatt** [comment]
Dear @Noemie-B,

Thanks for your interest in using spacemake! The error was introduced with `v0.5.4`, by introducing the `--version` option to the command line. I have fixed this, and will push the changes shortly, and upload a new version `v0.5.5` to pypi. Then, to use the fixed code, simply run `pip install --upgrade spacemake` which should install the fixed `v0.5.5`.

Best, Tamas

**Comment by Noemie-B** [comment]
Hi all, thanks a lot for your quick answers !

Unfortunately, when I try to upgrade pip it says that 0.5.4 is the latest version : 

(spacemake) user@user-Precision-7560:~/Code/test_visium$ pip install --upgrade spacemake
Requirement already satisfied: spacemake in /home/user/anaconda3/envs/spacemake/lib/python3.9/site-packages (0.5.4)

Thanks again for your help !

**Comment by Noemie-B** [comment]
It works now !
Thanks a lot @sztankatt ! Your help is really appreciated.

**Comment by sztankatt** [comment]
Dear @Noemie-B,

What operating system are you using?

I think the problem might be that you are trying to run spacemake with data on a pendrive, or external drive. Hence your path `/media/user/Seagate Expansion Drive/` contains spaces which is why most likely spacemake fails. 

I would suggest copying the files somewhere on your computer and then adding the samples to spacemake (now with the new path). The path should have no spaces in it.

Best,
Tamas

**Comment by Noemie-B** [comment]
Hi Tamas,
It works perfectly now. Thanks a lot for your help !
Best
Noemie
