### ISSUE TITLE
Possible error that produces empty panels in the qc_sheet

### ISSUE THREAD

**Issue by nukappa** [rajewsky-lab/spacemake#41]
The #genes/#UMIs/%mt/#reads/#beads_joined panels in the qc_sheet have correct values in the legend but all points are painted in gray. Might be related to commit 87f5858ce1fcdc5605895de50364386c1d171236, or to the PR #38 or both.

**Comment by nukappa** [comment]
@danilexn when you have time can you check if you reproduce this error?

**Comment by danilexn** [comment]
> @danilexn when you have time can you check if you reproduce this error?

Of course, will do it asap 😉

**Comment by nukappa** [comment]
Seems like the error comes from the `geom_hex` part of the following code

```
    if(is_hexagonal){
        pl <- spatial_qc_dat %>%
            ggplot(aes(x_pos, y_pos, fill = val, group=1)) +
                geom_hex(stat='identity', color='gray95') +
                guides(fill = guide_colorbar(barheight = 10)) + 
                labs(fill=ttl, x='', y='')
        if(cut_dist){
            pl <- pl +
                scale_fill_viridis_c(option =  "magma", limits = limits)
        } else {
            pl <- pl + 
                scale_fill_viridis_c(option =  "magma") 
        }
```

No clue if it's a problem because of a more recent `R` package (probably `tidyverse`) or something else. Setting `is_hexagonal=FALSE` at the end of the `.Rmd` solves it, since the `geom_point` behaves normally.

Eventually we want to migrate all these reports to Python, so I leave this as is right now here.

**Comment by nukappa** [comment]
Update: seems to be related to a `ggplot` issue described [here](https://github.com/tidyverse/ggplot2/issues/5037).
