### ISSUE TITLE
add/update_sample needs to validate --map_strategy 

### ISSUE THREAD

**Issue by marvin-jens** [rajewsky-lab/spacemake#54]
Currently, no validation of the `map_strategy` string is performed when adding or updating a sample. If a reference is used that does not exist in the `config.yaml`, this triggers a confusing `KeyError` in `mapping.smk` during `spacemake run`.

Expected behavior: An exception should be thrown when adding or updating a sample with an invalid map_strategy.

**Comment by nukappa** [comment]
We could use the `ConfigVariableNotFoundError` for this. Currently `map_strategy` is the only (important) project variable not defined in the `config.yaml`. How about we ship spacemake with a few default ones and provide cmd line support to add/update more strategies? It'll make it easier to catch errors, give a default to the user etc

**Comment by marvin-jens** [comment]
Hi Daniel, just to let you know, during fixing #88 oron fast-cmdline I've noticed that your commits introduced errors. `ConfigVariableNotFoundError` expected not just a string with the error message but also the name of the variable that was not found. Then, the way you used `map_strategy.validate_mapstr`, you turned a string into a list with a single string in it (`corrected_map_strategies.append(...)`). This caused breakage downstream. Let's all please make sure that `pytest -m "not big_download" tests/` runs through w/o issues before opening a PR. I should have checked that the tests finish, so joke's on me. However, with recent `fast-cmdline` all tests should now run (just tested on my laptop w/o /data/rajewsky ...).

**Comment by marvin-jens** [comment]
This being said, I kept your changes functionally intact. Will now create a branch to add a cmdline test to ensure that add/update_sample indeed validates and then close the issue as well.
