### ISSUE TITLE
List of joined spatial units in meshed adata

### ISSUE THREAD

**Issue by danilexn** [rajewsky-lab/spacemake#58]
In the function https://github.com/rajewsky-lab/spacemake/blob/350294686eeeeceab9c76500fa47d96750dea7fd/spacemake/spatial/util.py#L273-L281

The "meshed" `adata_out` object constitutes the main output, e.g.,

https://github.com/rajewsky-lab/spacemake/blob/350294686eeeeceab9c76500fa47d96750dea7fd/spacemake/spatial/util.py#L419-L422

For some analyses, it is relevant to have a list of spatial units that have been merged into each newly created mesh cell. That is, for each new cell in `adata_out,` a list of spots. This can be done by index (pointing to the .obs_names in the `adata` input), such that it can be stored as a sparse matrix where 1 denotes mapping.

I propose both of these lists can be stored as `adata_out.uns["indices_joined_spatial_units"]` and `adata_out.uns["spatial_units_obs_names"]`. The purpose of this second list is to keep track of the `adata.obs_names`, which could contain relevant information such as cell barcodes that can be traced back to the final `bam` file.

Edit 1:
It is important to modularize `spacemake.spatial.util.create_meshed_adata` by separating the mapping of spatial units to the mesh and the construction of the adata. This is helpful when integrating other types of spatial unit aggregation (e.g., supported by segmentation).

**Comment by nukappa** [comment]
Absolutely agree. And since you're onto this, I think we should also add barcode names for the meshed cells. Currently they are simply numbered. Using the `puck_name` (or tile etc) in addition to a number is more intuitive and useful in later stages where we stitch multiple tiles together.
