### ISSUE TITLE
Support for FFPE?

### ISSUE THREAD

**Issue by bernard2012** [rajewsky-lab/spacemake#62]
Hi, Thank you for making this user-friendly package. I am wondering if there is support for Visium FFPE data coming? Thanks.

**Comment by sztankatt** [comment]
Dear @bernard2012,

Thank you for using spacemake! In our publication we only tested spacemake on samples from fresh frozen tissue.

However, to my knowledge the data from fresh frozen or FFPE Visium are the same downstream (same barcodes, positions etc), so spacemake should work out of the box.

Here is a guide on how to process Visium samples: https://spacemake.readthedocs.io/en/latest/quick-start/index.html#visium-quick-start

Best,
Tamas

**Comment by marvin-jens** [comment]
@bernard2012 were you able to analyze FFPE data successfully?
