### ISSUE TITLE
samples not correctly read from yaml

### ISSUE THREAD

**Issue by liekevandehaar** [rajewsky-lab/spacemake#80]
Hi, I reinstalled spacemake from the master brach and tried to run spacemake with an old sample.yml file and an old config file. Both used to work correctly. Now when I load the sample.yml file using 

`spacemake projects add_samples_from_yaml --samples_yaml samples.yml `

I get the following error:
```

WARNING: run_mode visium lists polyA_adapter_trimming=false. This is no longer supported and will be overriden with true
WARNING: run_mode visium lists polyA_adapter_trimming=false. This is no longer supported and will be overriden with true
Adding sample ('FC_LH_03', 'FC_LH_03_07')
getting default for 'human' have_rRNA=True -> bowtie2:rRNA,STAR:genome:final
No --puck_barcode_file_id provided. Generating ids from filename
```
--------------------------------------------------
SUCCESS!

I attached the config file as a text doc. 

[config.txt](https://github.com/rajewsky-lab/spacemake/files/13645549/config.txt)

In the old yml file (removed paths) looks like this

[samples.txt](https://github.com/rajewsky-lab/spacemake/files/13645593/samples.txt)

Do you have any idea on whether something changed on the master branch? My code used to work with the latest version of spacemake pulled from pip.

**Comment by marvin-jens** [comment]
Hi Lieke, I try to reproduce the issue but can't find the read sequence files referenced in the samples.txt, because it contains relative paths. Could you please tell me the path on margaret you use to run the `spacemake projects add_samples_from_yaml` command from? Thx

**Comment by marvin-jens** [comment]
Working together with Lieke it turned out that the error was not reproducible. It now works with current master (0.7.3) for Lieke as well.
