### ISSUE TITLE
`name` added to config.yaml when creating a new run mode

### ISSUE THREAD

**Issue by nukappa** [rajewsky-lab/spacemake#88]
Leaving this here so we don't forget. For example, running `spacemake config add_run_mode --name newrunmode` will add the following to `config.yaml`:

```
  newrunmode:
    name: newrunmode
    spatial_barcode_min_matches: 0
```

Not sure if it matters downstream though, i.e. if the `name` is used somewhere. To be updated.

**Comment by nukappa** [comment]
Can verify that it doesn't matter for downstream analysis. Also adding a 2nd `run_mode` will add a `name` to the newest run mode and will remove it from the one previously added.

**Comment by marvin-jens** [comment]
it is fixed now on fast-cmdline, which is going to be merged with master soonish, so Im closing this issue
